### ISSUE TITLE
Basic regular expression doesn't work

### ISSUE THREAD

**Issue by dp-ck** [aaditmshah/regex#1]
This basic regular expression doesn't seem to be working: [a-zA-Z0-9_]*

var word = 'DiegoPardo12'
var reg = /[a-zA-Z0-9_]*/;
var regex = new Regex(reg);
if(regex.test(word))... is always false

Thanks!

**Comment by arthurstomp** [comment]
Happened the same with me.

``` javascript
var word = 'ws://';
var reg = /(ws:\/\/)/;
var regex = new Regex(reg);
console.log(regex.test(word)); // always false :/
```

**Comment by ORESoftware** [comment]
yikes

**Comment by aaditmshah** [comment]
It doesn't work because I haven't implemented it. Sorry. I'm a little busy with college work nowadays. Hence, I might not be able to fix this issue anytime soon.
